set_component Display_Controller_C0
set_false_path -from [ get_cells { */*/*/*ctrl_reg*}]
set_false_path -from [ get_cells { */*/*/*hres*}]
set_false_path -from [ get_cells { */*/*/*vres*}]
set_false_path -from [ get_cells { */*/*/*hf_porch*}]
set_false_path -from [ get_cells { */*/*/*hb_porch*}]
set_false_path -from [ get_cells { */*/*/*vf_porch*}]
set_false_path -from [ get_cells { */*/*/*vf_porch1*}]
set_false_path -from [ get_cells { */*/*/*vf_porch2*}]
set_false_path -from [ get_cells { */*/*/*vb_porch*}]
set_false_path -from [ get_cells { */*/*/*vb_porch1*}]
set_false_path -from [ get_cells { */*/*/*vb_porch2*}]
set_false_path -from [ get_cells { */*/*/*hsync_width*}]
set_false_path -from [ get_cells { */*/*/*vsync_width*}]
set_false_path -from [ get_cells { */*/*/*vsync_width1*}]
set_false_path -from [ get_cells { */*/*/*vsync_width2*}]
set_false_path -through [ get_pins { */*/*/*mem_rd_data*}]
